# Generated by Django 4.0.4 on 2022-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_image_remove_home_brend_remove_home_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('imag', models.ImageField(upload_to='')),
            ],
        ),
    ]
