# Generated by Django 4.0.4 on 2022-06-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_imag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imag',
        ),
    ]
