# Generated by Django 4.0.4 on 2022-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_chart_number_chart_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='link',
            field=models.CharField(default=1, max_length=230),
            preserve_default=False,
        ),
    ]
