# Generated by Django 4.0.4 on 2022-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_chart_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='brend',
            field=models.CharField(default=1, max_length=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='car',
            field=models.CharField(default=1, max_length=102),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='title',
            field=models.CharField(default=1, max_length=129),
            preserve_default=False,
        ),
    ]
