# Generated by Django 4.0.4 on 2022-06-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_chart_brend_chart_car_chart_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
